// <auto-generated>
// Rewired Constants
// This list was generated on 2020-02-01 4:02:58 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "GameplayStart")]
        public const int GameplayStart = 5;
        // MainGameplay
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "MainGameplay", friendlyName = "Rotate")]
        public const int Rotate = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "MainGameplay", friendlyName = "Move Forward and Backward")]
        public const int Move = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "MainGameplay", friendlyName = "Dash")]
        public const int Dash = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "MainGameplay", friendlyName = "Pick up a block")]
        public const int PickUpBlock = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "MainGameplay", friendlyName = "Dump block on ground")]
        public const int DumpBlock = 4;
        // TetrisGameplay
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "TetrisGameplay", friendlyName = "Place block")]
        public const int PlaceBlock = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "TetrisGameplay", friendlyName = "Cancel Place Block")]
        public const int CancelPlaceBlock = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "TetrisGameplay", friendlyName = "Rotate Block")]
        public const int RotateBlock = 12;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "TetrisGameplay", friendlyName = "Move Block on X axis")]
        public const int MoveBlockX = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "TetrisGameplay", friendlyName = "Move Block on Y axis")]
        public const int MoveBlockY = 11;
    }
    public static partial class Category {
        public const int Default = 0;
        public const int MainGameplay = 1;
        public const int TetrisGameplay = 2;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int Player0 = 0;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player1")]
        public const int Player1 = 1;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player2")]
        public const int Player2 = 2;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player3")]
        public const int Player3 = 3;
    }
    public static partial class MapEnablerRuleSet {
        public const int Gameplay = 1;
        public const int TetrisGameplay = 2;
    }
}
